# Generated by Django 2.0 on 2018-02-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20180216_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='user_sex',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('Male', 'Male'), ('Female', 'Female')], default=None, max_length=20),
        ),
    ]
