# Generated by Django 2.0 on 2018-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20180216_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tldr',
            field=models.TextField(default='fill in input here', max_length=1000),
            preserve_default=False,
        ),
    ]
